services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sisie_opsise_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
